### ISSUE TITLE
config flow failed to load

### ISSUE THREAD

**Issue by khiles** [mjoshd/hyperhdr-ha#4]
Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 19:39:57 (4 occurrences)
Last logged: 19:44:59

Error occurred loading configuration flow for integration hyperhdr: cannot import name 'Platform' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

getting the above error in home assistant

**Comment by mjoshd** [comment]
I'll look into it when I have time (probably this weekend).

Until then, please do the following:
- uninstall the HyperHDR integration via HACS
- restart Home Assistant
- ensure you are running the latest Home Assistant (currently 2021.12.10)
- install the 0.0.2 version of the HyperHDR integration via HACS (choose from the dropdown)
- restart Home Assistant
- configure the HyperHDR integration as normal

Be aware, the camera stream sensor doesn't work in 0.0.2 because of changes in HA but initial setup/configuration should work fine. You can disable the camera stream sensor afterward to keep errors/warnings out of the logs.

Honestly, the camera stream sensor is pretty buggy/unreliable and I'm probably going to remove it from the next version.

**Comment by mjoshd** [comment]
I had some free time this morning so I did some updates.

I tested multiple times and v0.0.4 goes through the config flow perfectly.
